image: docker-registry.int.aisingapore.org/gitlab-runner-base:latest

before_script:
  - pip install --upgrade pip
  - pip install pandas
  - pip install scikit-learn

golden-retriever-test:
  script:
    - python -m pytest

# corgi-test:
#   script:
#     - ./test.py